services:
  web:
    # image: httpd
    build: 
      context: .
      dockerfile: web.dockerfile
    ports: 
      - 6969:80
    # volumes:
    #   - ./html:/var/www/html
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress
    volumes:
      - kit23dbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  kit23dbdata: